/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_exaple_fragment_Fragment0 */

#ifndef _Included_com_exaple_fragment_Fragment0
#define _Included_com_exaple_fragment_Fragment0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_exmaple_roomlightdemo_nativeclass_LightNative
 * Method:    openLightDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_exaple_allnative_LightNative_openLightDev
  (JNIEnv *, jclass);

/*
 * Class:     com_exmaple_roomlightdemo_nativeclass_LightNative
 * Method:    opLight
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_exaple_allnative_LightNative_opLight
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_exmaple_roomlightdemo_nativeclass_LightNative
 * Method:    closeLightDev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_exaple_allnative_LightNative_closeLightDev
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
