/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_uhomeserver_nativeclass_CurtainNative */

#ifndef _Included_com_exaple_fragment_Fragment2_CurtainNative
#define _Included_com_exaple_fragment_Fragment2_CurtainNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_uhomeserver_nativeclass_CurtainNative
 * Method:    openCurtainDev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_exaple_allnative_CurtainNative_openCurtainDev
  (JNIEnv *, jclass);

/*
 * Class:     com_example_uhomeserver_nativeclass_CurtainNative
 * Method:    changeCurtainDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_exaple_allnative_CurtainNative_changeCurtainDev
(JNIEnv *, jclass , jint , jint );

/*
 * Class:     com_example_uhomeserver_nativeclass_CurtainNative
 * Method:    closeCurtainDev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_exaple_allnative_CurtainNative_closeCurtainDev
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
