/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_smarthome_nativeclass_DcmotorNative */

#ifndef _Included_com_exaple_fragment_Fragment1_DcmotorNative
#define _Included_com_exaple_fragment_Fragment1_DcmotorNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_smarthome_nativeclass_DcmotorNative
 * Method:    openDcMotorDev
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_exaple_allnative_DcmotorNative_openDcMotorDev
  (JNIEnv *, jclass);

/*
 * Class:     com_example_smarthome_nativeclass_DcmotorNative
 * Method:    opDcMotorDev
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_exaple_allnative_DcmotorNative_opDcMotorDev
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_smarthome_nativeclass_DcmotorNative
 * Method:    closeDcMotorDev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_exaple_allnative_DcmotorNative_closeDcMotorDev
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
