/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myjni_nativeclass_LightSensorNative */

#ifndef _Included_com_exaple_fragment_Fragment3_LightSensorNative
#define _Included_com_exaple_fragment_Fragment3_LightSensorNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myjni_nativeclass_LightSensorNative
 * Method:    openLightSenseDev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_exaple_allnative_LightSenserNative_openLightSenseDev
  (JNIEnv *, jclass);

/*
 * Class:     com_example_myjni_nativeclass_LightSensorNative
 * Method:    nowLightSense
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_exaple_allnative_LightSenserNative_nowLightSense
  (JNIEnv *, jclass);

/*
 * Class:     com_example_myjni_nativeclass_LightSensorNative
 * Method:    closeLightSenseDev
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_exaple_allnative_LightSenserNative_closeLightSenseDev
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
