/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_gettempdemo_nativeclass_TempNative */

#ifndef _Included_com_exaple_fragment_Fragment3_TempNative
#define _Included_com_exaple_fragment_Fragment3_TempNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gettempdemo_nativeclass_TempNative
 * Method:    openHumidity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_exaple_allnative_TempNative_openHumidity
  (JNIEnv *, jclass);

/*
 * Class:     com_example_gettempdemo_nativeclass_TempNative
 * Method:    readHumidityValue
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_exaple_allnative_TempNative_readHumidityValue
  (JNIEnv *, jclass);

/*
 * Class:     com_example_gettempdemo_nativeclass_TempNative
 * Method:    closeHumidity
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_exaple_allnative_TempNative_closeHumidity
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
